# Tuning and training the models for standard-pHLA-score

Input are the per-peptide-position ref2015 features for complex, already generated in ../Featurization/rosettaPPPEnergies.csv

We tune the parameters in the 5-fold-crossvalidation setting.

In [2]:
import pandas as pd
import numpy as np

from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import KFold
import time
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import ParameterSampler, cross_val_score
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from IPython.display import display
from scipy import stats
import _pickle as cPickle
import statistics
from sklearn.linear_model import LinearRegression
from sklearn import linear_model
from sklearn.kernel_ridge import KernelRidge
from sklearn.cross_decomposition import PLSRegression

## Load the standard ref2015 features

### Full dataset

In [3]:
## 1 - load the energies
def pppene_to_array(tmp):
    tmp = tmp.replace("(", "")
    tmp = tmp.replace(")", "")
    tmp = tmp.strip("[]")
    tmp = tmp.replace(" ", "")
    tmp = tmp.replace("\n", ",")
    return np.fromstring(tmp, dtype=float, sep=", ").reshape(9,20)

ppp_ene = pd.read_csv("../Featurization/rosettaPPPEnergies.csv")
ppp_ene = ppp_ene[["allele", "peptide", "binder", "ba", "energies", "total_energy"]]
ppp_ene["energies"] = ppp_ene["energies"].apply(pppene_to_array)
ppp_ene

allele    peptide  binder        ba  \
0      A0101  YLEQLHQLY       1  0.574375   
1      A0101  HSERHVLLY       1  0.574375   
2      A0101  MTDPEMVEV       1  0.574375   
3      A0101  LTDFIREEY       1  0.574375   
4      A0101  LLDQRPAWY       1  0.574375   
...      ...        ...     ...       ...   
77576  C1601  QQTTTSFQN       0  0.000000   
77577  C1601  QQVEQMEIP       0  0.000000   
77578  C1601  QQWQVFSAE       0  0.000000   
77579  C1601  QRCVVLRFL       0  0.000000   
77580  C1601  QRISFEVLA       0  0.000000   

                                                energies  total_energy  
0      [[-9.37669305, 4.67802037, 8.54111444, 10.3367...    112.623867  
1      [[-7.89190954, 0.93707113, 10.06233605, 2.7158...     91.902185  
2      [[-8.25236275, 10.56587939, 7.5793572, 1.14710...    146.451590  
3      [[-8.43720197, 10.21830335, 7.113905, 36.51672...    138.735082  
4      [[-8.18944861, 12.37002534, 6.69837214, 8.0238...    142.756344  
...                                                  ...           ...  
77576  [[-8.23468271, 4.14167228, 9.40648541, 38.0082...    128.349704  
77577  [[-9.20362039, 22.89414572, 10.40234849, 35.70...    159.872992  
77578  [[-8.46025926, 3.82365938, 10.25920191, 61.414...     97.152888  
77579  [[-7.11160825, 1.35151526, 9.62650699, 20.2230...    116.714004  
77580  [[-8.46216776, 5.91464051, 9.83828238, 45.0747...    112.405199  

[77581 rows x 6 columns]

### Map the full dataset to the training set

In [4]:
#Load split
train_set = pd.read_csv("../Datasets/train_set.csv")
train_set = train_set[["allele", "peptide", "fileloc", "allele_type", "fold_num"]]

#Merge to form the training set
train_dataset = pd.merge(ppp_ene, train_set, on=["allele", "peptide"], suffixes=["", "_y"], how="inner")
train_dataset

allele    peptide  binder        ba  \
0      A0101  YLEQLHQLY       1  0.574375   
1      A0101  HSERHVLLY       1  0.574375   
2      A0101  MTDPEMVEV       1  0.574375   
3      A0101  LTDFIREEY       1  0.574375   
4      A0101  LLDQRPAWY       1  0.574375   
...      ...        ...     ...       ...   
69793  C1601  QQTTTSFQN       0  0.000000   
69794  C1601  QQVEQMEIP       0  0.000000   
69795  C1601  QQWQVFSAE       0  0.000000   
69796  C1601  QRCVVLRFL       0  0.000000   
69797  C1601  QRISFEVLA       0  0.000000   

                                                energies  total_energy  \
0      [[-9.37669305, 4.67802037, 8.54111444, 10.3367...    112.623867   
1      [[-7.89190954, 0.93707113, 10.06233605, 2.7158...     91.902185   
2      [[-8.25236275, 10.56587939, 7.5793572, 1.14710...    146.451590   
3      [[-8.43720197, 10.21830335, 7.113905, 36.51672...    138.735082   
4      [[-8.18944861, 12.37002534, 6.69837214, 8.0238...    142.756344   
...                                                  ...           ...   
69793  [[-8.23468271, 4.14167228, 9.40648541, 38.0082...    128.349704   
69794  [[-9.20362039, 22.89414572, 10.40234849, 35.70...    159.872992   
69795  [[-8.46025926, 3.82365938, 10.25920191, 61.414...     97.152888   
69796  [[-7.11160825, 1.35151526, 9.62650699, 20.2230...    116.714004   
69797  [[-8.46216776, 5.91464051, 9.83828238, 45.0747...    112.405199   

                                                 fileloc allele_type  fold_num  
0      /home/anja/Documents/jayvee_data/singleconf/al...       HLA-A       2.0  
1      /home/anja/Documents/jayvee_data/singleconf/al...       HLA-A       0.0  
2      /home/anja/Documents/jayvee_data/singleconf/al...       HLA-A       0.0  
3      /home/anja/Documents/jayvee_data/singleconf/al...       HLA-A       1.0  
4      /home/anja/Documents/jayvee_data/singleconf/al...       HLA-A       1.0  
...                                                  ...         ...       ...  
69793  /home/anja/Documents/COMP590P/C_decoys/confs/C...       HLA-C       4.0  
69794  /home/anja/Documents/COMP590P/C_decoys/confs/C...       HLA-C       4.0  
69795  /home/anja/Documents/COMP590P/C_decoys/confs/C...       HLA-C       1.0  
69796  /home/anja/Documents/COMP590P/C_decoys/confs/C...       HLA-C       2.0  
69797  /home/anja/Documents/COMP590P/C_decoys/confs/C...       HLA-C       3.0  

[69798 rows x 9 columns]

In [5]:
# extracting features in training format
# and get the cross-validation iterator
def get_energies(X):
    ene = np.roll(X, 4, axis = 0)[:9,:19]
    ene = np.roll(ene, -4, axis = 0)
    ene = ene.reshape(9*19)
    return ene

def extract_features_Xy_cv(merged_df, allele):
    allele_data = merged_df[merged_df["allele"]==allele]
    allele_data["enefeat"] = allele_data["energies"].apply(get_energies)
    allele_data = allele_data.reset_index(drop=True)
    flag = 0
    for index, row in allele_data.iterrows():
        if flag == 0:
            X = np.array(row['enefeat'])
            flag = 1
        else: 
            X = np.vstack((X, row['enefeat']))
    #extract binding energies        
    y = np.array(list(allele_data["ba"]))
    y_l = np.array(list(allele_data["binder"]))
    
    cv_iter = []
    for split in range(5):
        test_ind = allele_data.index[(allele_data['fold_num'] == split)].tolist()
        train_ind = allele_data.index[~(allele_data['fold_num'] == split)].tolist()
        cv_iter.append((train_ind, test_ind))
        
    return (X, y, y_l, cv_iter)
    


In [6]:
def param_tune_allele(allele, train_dataset):
    
    allele_td = train_dataset[train_dataset["allele"]==allele]
    (X_train, y_train, y_l, cv) = extract_features_Xy_cv(allele_td, allele)

    grid_params = {'n_components': [2, 5, 10, 100]
            }
    
    regr_results = {}
    best_cv_mscore = 0
    best_cv_scores = None
    best_cv_params = None
    regr_pls = PLSRegression()
    
    for i, g in enumerate(ParameterSampler(grid_params, n_iter=4)):
        print("CV")
        print(g)
        #cross-validation
        regr_pls.set_params(**g)
        cv_scores = cross_val_score(regr_pls, X_train, y_train, cv=cv, n_jobs = -1)
        cv_mscore = statistics.mean(cv_scores)
        print(cv_scores)
        print(cv_mscore)
        if cv_mscore > best_cv_mscore:
            best_cv_params = g
            best_cv_scores = cv_scores
  
    print("Best CV "+str(best_cv_mscore))
    print(best_cv_params)
    return (None, None, best_cv_params, best_cv_scores)
            
    
'''
    regr_oob = RandomForestRegressor(n_jobs=-1)
    regr_cv = RandomForestRegressor(n_jobs=-1)

    best_oob_score = 0 
    best_oob_params = None
    best_cv_mscore = 0
    best_cv_scores = None
    best_cv_params = None
    for i, g in enumerate(ParameterSampler(grid_params, n_iter=100)):
        print("Parameter iteration: "+str(i))
        print("OOB")
        #out of bag
        print(g)
        regr_oob.set_params(**g)
        regr_oob.fit(X_train_s,y_train_s)
        print(regr_oob.oob_score_)
        if regr_oob.oob_score_ > best_oob_score:
            best_oob_params = g
            best_oob_score = regr_oob.oob_score_
        
        print("CV")
        #cross-validation
        regr_cv.set_params(**g)
        cv_scores = cross_val_score(regr_cv, X_train, y_train, cv=cv, n_jobs = -1)
        cv_mscore = statistics.mean(cv_scores)
        print(cv_scores)
        print(cv_mscore)
        if cv_mscore > best_cv_mscore:
            best_cv_params = g
            best_cv_scores = cv_scores
            best_cv_mscore = cv_mscore
            
    print("Best OOB "+str(best_oob_score))
    print(best_oob_params)
    print("Best CV "+str(best_cv_mscore))
    print(best_cv_params)
    return (best_oob_params, best_oob_score, best_cv_params, best_cv_scores)

'''

'\n    regr_oob = RandomForestRegressor(n_jobs=-1)\n    regr_cv = RandomForestRegressor(n_jobs=-1)\n\n    best_oob_score = 0 \n    best_oob_params = None\n    best_cv_mscore = 0\n    best_cv_scores = None\n    best_cv_params = None\n    for i, g in enumerate(ParameterSampler(grid_params, n_iter=100)):\n        print("Parameter iteration: "+str(i))\n        print("OOB")\n        #out of bag\n        print(g)\n        regr_oob.set_params(**g)\n        regr_oob.fit(X_train_s,y_train_s)\n        print(regr_oob.oob_score_)\n        if regr_oob.oob_score_ > best_oob_score:\n            best_oob_params = g\n            best_oob_score = regr_oob.oob_score_\n        \n        print("CV")\n        #cross-validation\n        regr_cv.set_params(**g)\n        cv_scores = cross_val_score(regr_cv, X_train, y_train, cv=cv, n_jobs = -1)\n        cv_mscore = statistics.mean(cv_scores)\n        print(cv_scores)\n        print(cv_mscore)\n        if cv_mscore > best_cv_mscore:\n            best_cv_params 

## Crossvalidation

In [7]:
alleles = train_dataset["allele"].unique()
results = {"allele":[], "best_oob_param":[], "best_oob_score":[], "best_cv_param":[], "best_cv_scores":[]}

for allele in alleles:
    print("------------------------------------------------------------------------")
    print("ALLELE")
    print(allele)
    res = param_tune_allele(allele, train_dataset)
    results["allele"].append(allele)
    results["best_oob_param"].append(res[0])
    results["best_oob_score"].append(res[1])
    results["best_cv_param"].append(res[2])
    results["best_cv_scores"].append(res[3])
    allele_train_dataset = train_dataset[train_dataset["allele"]==allele]
    (X_train, y_train, y_l, cv) = extract_features_Xy_cv(allele_train_dataset, allele)
    regr_best = PLSRegression()
    regr_best.set_params(**res[2])
    regr_best.fit(X_train, y_train)
    with open('./final_PLS_REGRmodels/'+allele+"ppp"+'.pkl', 'wb') as fid:
        cPickle.dump(regr_best, fid)  

------------------------------------------------------------------------
ALLELE
A0101
CV
{'n_components': 2}
[0.67232852 0.73948943 0.67043684 0.68697219 0.73611312]
0.7010680210809027
CV
{'n_components': 5}
[0.66647446 0.75493178 0.69263154 0.7003825  0.73641222]
0.7101664989701151
CV
{'n_components': 10}
[0.680768   0.75681059 0.69491994 0.70862184 0.71353476]
0.71093102479126
CV
{'n_components': 100}
[0.67887173 0.75723703 0.69583321 0.70698154 0.7121259 ]
0.7102098843982851
Best CV 0
{'n_components': 100}
------------------------------------------------------------------------
ALLELE
A0201
CV
{'n_components': 2}
[0.6418109  0.62954635 0.62400398 0.6401948  0.62462109]
0.6320354234215495
CV
{'n_components': 5}
[0.66567758 0.64631655 0.6327235  0.65352459 0.64851756]
0.6493519573547379
CV
{'n_components': 10}
[0.66784489 0.64934688 0.63151085 0.66060293 0.65377249]
0.6526156102955637
CV
{'n_components': 100}
[0.67013038 0.64863095 0.63160198 0.6613495  0.65509365]
0.653361290672819
B

------------------------------------------------------------------------
ALLELE
B1801
CV
{'n_components': 2}
[0.6385428  0.66558388 0.64067566 0.67683261 0.67888335]
0.6601036595332397
CV
{'n_components': 5}
[0.67831357 0.70595978 0.6966813  0.72518561 0.6971622 ]
0.7006604895515351
CV
{'n_components': 10}
[0.68683587 0.72557925 0.7076522  0.73783377 0.69538064]
0.7106563482137028
CV
{'n_components': 100}
[0.69289601 0.72813074 0.71147112 0.73837155 0.6952719 ]
0.713228263201195
Best CV 0
{'n_components': 100}
------------------------------------------------------------------------
ALLELE
B2705
CV
{'n_components': 2}
[0.69571339 0.64958497 0.7332119  0.67925735 0.66232087]
0.6840176957740082
CV
{'n_components': 5}
[0.70325526 0.65778051 0.75010618 0.70392866 0.67583238]
0.6981805972203864
CV
{'n_components': 10}
[0.70084403 0.66225982 0.755855   0.70376382 0.67394981]
0.6993344971397655
CV
{'n_components': 100}
[0.70089537 0.66526383 0.75730704 0.70583654 0.67240085]
0.7003407256201956

In [8]:
results_df = pd.DataFrame(results)
results_df.to_pickle("crossval_ppp_PLS.pkl")
results_df.to_csv("crossval_ppp_PLS.csv")
results_df

allele best_oob_param best_oob_score          best_cv_param  \
0   A0101           None           None  {'n_components': 100}   
1   A0201           None           None  {'n_components': 100}   
2   A0203           None           None  {'n_components': 100}   
3   A0206           None           None  {'n_components': 100}   
4   A0301           None           None  {'n_components': 100}   
5   A1101           None           None  {'n_components': 100}   
6   A2301           None           None   {'n_components': 10}   
7   A2402           None           None  {'n_components': 100}   
8   A2601           None           None  {'n_components': 100}   
9   A2902           None           None  {'n_components': 100}   
10  A3101           None           None  {'n_components': 100}   
11  A6801           None           None  {'n_components': 100}   
12  A6802           None           None  {'n_components': 100}   
13  B0702           None           None  {'n_components': 100}   
14  B0801           None           None  {'n_components': 100}   
15  B1501           None           None  {'n_components': 100}   
16  B1801           None           None  {'n_components': 100}   
17  B2705           None           None  {'n_components': 100}   
18  B3501           None           None  {'n_components': 100}   
19  B3901           None           None  {'n_components': 100}   
20  B4001           None           None  {'n_components': 100}   
21  B4002           None           None  {'n_components': 100}   
22  B4403           None           None  {'n_components': 100}   
23  B5101           None           None  {'n_components': 100}   
24  B5701           None           None  {'n_components': 100}   
25  C0304           None           None  {'n_components': 100}   
26  C0501           None           None  {'n_components': 100}   
27  C1601           None           None  {'n_components': 100}   

                                       best_cv_scores  
0   [0.6788717293181386, 0.7572370334900203, 0.695...  
1   [0.6701303779601218, 0.6486309460033863, 0.631...  
2   [0.6424024418775794, 0.6994552598824978, 0.660...  
3   [0.6489907519963619, 0.6542775599996109, 0.634...  
4   [0.6549979589655925, 0.6898969850670456, 0.647...  
5   [0.6780471526650106, 0.780372823609928, 0.7820...  
6   [0.6880159606779881, 0.6786748315505192, 0.656...  
7   [0.6166002055817125, 0.5827645218330157, 0.526...  
8   [0.6010319301575893, 0.6254533358918724, 0.550...  
9   [0.6359378626381005, 0.6662959536822017, 0.219...  
10  [0.6881017140488843, 0.6648605067852658, 0.709...  
11  [0.8039983166710758, 0.7505999101693615, 0.795...  
12  [0.5843223625245414, 0.5265586641616307, 0.533...  
13  [0.6603479637422002, 0.6465313565801701, 0.677...  
14  [0.6172705386254715, 0.6753693872931558, 0.621...  
15  [0.5333344224215624, 0.5260848551188315, 0.512...  
16  [0.6928960073969093, 0.7281307432882277, 0.711...  
17  [0.7008953705256584, 0.6652638289918245, 0.757...  
18  [0.5565573288154435, 0.56088141154358, 0.56595...  
19  [0.6006899090194846, 0.5948089254842631, 0.650...  
20  [0.7223114517232176, 0.6969937959611098, 0.703...  
21  [0.4810583969510564, 0.554328255566052, 0.5484...  
22  [0.6814053293436741, 0.7356970005589032, 0.699...  
23  [0.6134282572691184, 0.5669819554093385, 0.461...  
24  [0.6419474050488388, 0.6499020498967396, 0.621...  
25  [0.7145539480906599, 0.7513784340538935, 0.612...  
26  [0.7963481726929218, 0.7953972797800399, 0.806...  
27  [0.6017599728070018, 0.71053559212485, 0.61594...

## Tune the best

In [ ]:
def train_best_model(allele, params, exp_name):
    allele_train_dataset = train_dataset[train_dataset["allele"]==allele]
    (X_train, y_train, y_l, cv) = extract_features_Xy_cv(allele_train_dataset, allele)
    regr_best = KernelRidge()
    regr_best.set_params(**params)
    regr_best.fit(X_train, y_train)
    with open('./final_PLS_REGRmodels/'+allele+exp_name+'.pkl', 'wb') as fid:
        cPickle.dump(regr_best, fid)    

In [ ]:
results_df = pd.DataFrame(results)
for allele in alleles:
    params = list(results_df[results_df["allele"]==allele]["best_cv_param"])[0]
    train_best_model(allele, params, "ppp")   

In [ ]:
results_df

## --------------------------------------------------- ##
## The middle/anchor position experiments are done for RF only 

## Middle position

In [13]:
# extracting features in training format
# and get the cross-validation iterator
def get_energies(X):
    ene = np.roll(X, -3, axis = 0)[:4,:19]
    ene = ene.reshape(4*19)
    return ene

In [ ]:
alleles = train_dataset["allele"].unique()
results = {"allele":[], "best_oob_param":[], "best_oob_score":[], "best_cv_param":[], "best_cv_scores":[]}

for allele in alleles:
    print("------------------------------------------------------------------------")
    print("ALLELE")
    print(allele)
    res = param_tune_allele(allele, train_dataset)
    results["allele"].append(allele)
    results["best_oob_param"].append(res[0])
    results["best_oob_score"].append(res[1])
    results["best_cv_param"].append(res[2])
    results["best_cv_scores"].append(res[3])

In [ ]:
def train_best_model(allele, params, exp_name):
    allele_train_dataset = train_dataset[train_dataset["allele"]==allele]
    (X_train, y_train, y_l, cv) = extract_features_Xy_cv(allele_train_dataset, allele)
    regr_best = RandomForestRegressor(n_jobs=-1)
    regr_best.set_params(**params)
    regr_best.fit(X_train, y_train)
    with open('./final_REGRmodels/'+allele+exp_name+'.pkl', 'wb') as fid:
        cPickle.dump(regr_best, fid)    

In [ ]:
for allele in alleles:
    params = list(results_df[results_df["allele"]==allele]["best_cv_param"])[0]
    train_best_model(allele, params, "ppp-middle") 

## Anchor positions

In [14]:
# extracting features in training format
# and get the cross-validation iterator
def get_energies(X):
    ene = np.roll(X, 2, axis = 0)[:5,:19]
    ene = np.roll(ene, -2, axis = 0)
    ene = ene.reshape(5*19)
    return ene

In [ ]:
alleles = train_dataset["allele"].unique()
results = {"allele":[], "best_oob_param":[], "best_oob_score":[], "best_cv_param":[], "best_cv_scores":[]}

for allele in alleles:
    print("------------------------------------------------------------------------")
    print("ALLELE")
    print(allele)
    res = param_tune_allele(allele, train_dataset)
    results["allele"].append(allele)
    results["best_oob_param"].append(res[0])
    results["best_oob_score"].append(res[1])
    results["best_cv_param"].append(res[2])
    results["best_cv_scores"].append(res[3])

In [ ]:
def train_best_model(allele, params, exp_name):
    allele_train_dataset = train_dataset[train_dataset["allele"]==allele]
    (X_train, y_train, y_l, cv) = extract_features_Xy_cv(allele_train_dataset, allele)
    regr_best = RandomForestRegressor(n_jobs=-1)
    regr_best.set_params(**params)
    regr_best.fit(X_train, y_train)
    with open('./final_REGRmodels/'+allele+exp_name+'.pkl', 'wb') as fid:
        cPickle.dump(regr_best, fid)

In [ ]:
for allele in alleles:
    params = list(results_df[results_df["allele"]==allele]["best_cv_param"])[0]
    train_best_model(allele, params, "ppp-anchor") 